# This file was generated by GoReleaser. DO NOT EDIT.
cask "goplaces" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "16ec02348faa3a549bd1586fed1128c543e61e1352ce12b7d0874cb65bd0d394"
      url "https://github.com/openclaw/goplaces/releases/download/v#{version}/goplaces_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "af76c026403e93ac95236340ae37fa53a0331ee83950e0563ac3ff5adfe24dfc"
      url "https://github.com/openclaw/goplaces/releases/download/v#{version}/goplaces_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a693e598a567dba7415241141eb40c8fe7ab0e5d282b7cbc37a9b3b760f3f634"
      url "https://github.com/openclaw/goplaces/releases/download/v#{version}/goplaces_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "40d794060e75b801c1a3bf80a1315e767615abc4625bd17adbc9d7688e224f1e"
      url "https://github.com/openclaw/goplaces/releases/download/v#{version}/goplaces_#{version}_linux_arm64.tar.gz"
    end
  end

  name "goplaces"
  desc "Modern Go client + CLI for the Google Places API (New)."
  homepage "https://github.com/openclaw/goplaces"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goplaces"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goplaces"]
    end
  end

  # No zap stanza required

end
