# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crabbox < Formula
  desc "Remote Linux test boxes for dirty worktrees and CI hydration"
  homepage "https://github.com/openclaw/crabbox"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/crabbox/releases/download/v0.3.1/crabbox_0.3.1_darwin_amd64.tar.gz"
      sha256 "6a9a91e1b599b88aaa7e4d7dacdd3e39c97fcf2f026d33545292fdd2fd764479"

      define_method(:install) do
        bin.install "crabbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/crabbox/releases/download/v0.3.1/crabbox_0.3.1_darwin_arm64.tar.gz"
      sha256 "66e303ec936a8b27edd77b1d83dff796f4ba0c27af51cb5fadfc0cd2e35278a1"

      define_method(:install) do
        bin.install "crabbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v0.3.1/crabbox_0.3.1_linux_amd64.tar.gz"
      sha256 "88d04c5b5f8e91134d20378893b73118a40c07cd718e9c44172a8cf74518cebe"
      define_method(:install) do
        bin.install "crabbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v0.3.1/crabbox_0.3.1_linux_arm64.tar.gz"
      sha256 "f2793087ba3be3722ccb57f0e44a6cc5f1409013f5e5644299fa018b9aed9be7"
      define_method(:install) do
        bin.install "crabbox"
      end
    end
  end

  test do
    system bin/"crabbox", "--version"
  end
end
