# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goplaces < Formula
  desc "Modern Go client + CLI for the Google Places API (New)."
  homepage "https://github.com/openclaw/goplaces"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.3/goplaces_0.4.3_darwin_amd64.tar.gz"
      sha256 "a6a3fee385a0491fad1d05b9ce6ab631322e8a058f2a8961465dc2097b702287"

      define_method(:install) do
        bin.install "goplaces"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.3/goplaces_0.4.3_darwin_arm64.tar.gz"
      sha256 "6b477d1fade3aa467031d537e43f9aa66704e100180f29d190cbf695fe1e8039"

      define_method(:install) do
        bin.install "goplaces"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.3/goplaces_0.4.3_linux_amd64.tar.gz"
      sha256 "d9d051fc3ee1c57d0853a90795f67ff19bab2474ceb5a7167bed1a56c7652396"
      define_method(:install) do
        bin.install "goplaces"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.3/goplaces_0.4.3_linux_arm64.tar.gz"
      sha256 "8d8cb6566c73dc83ffe0fc354e0432e4ee6737caa29c7247c6aaa121397819f2"
      define_method(:install) do
        bin.install "goplaces"
      end
    end
  end

  test do
    system "#{bin}/goplaces", "--version"
  end
end
